service: ms-${self:custom.serviceName}
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: 'us-east-1'
  stage: ${opt:stage, "${env:stage, 'dev'}"}
  memorySize: 512
  apiGateway:
    restApiId: ${ssm:/destaka/infra/api-gateway/id}
    restApiRootResourceId: ${ssm:/destaka/infra/api-gateway/root-resource-id}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:CreateTable
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 'arn:aws:dynamodb:${aws:region}:${aws:accountId}:*'
  environment:
      STAGE: ${self:provider.stage}
      REGION: ${self:provider.region}

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  esbuild:
    bundle: true
    minify: false
  serviceName: events
  contextPath: ${self:custom.serviceName}
  baseApi: ${self:custom.contextPath}
  funcDir: src/framework/functions
  ms-account-authorizer:
    type: TOKEN
    authorizerId: ${ssm:/destaka/ms-auth/authorizer-id}

functions:
  createEvent:
    handler: ${self:custom.funcDir}/createEvent.handler
    events:
      - http:
          path: ${self:custom.baseApi}/
          method: post
          authorizer: ${self:custom.ms-account-authorizer}
          cors:
            origin: '*'
            headers: '*'
  getEvent:
    handler: ${self:custom.funcDir}/getEvent.handler
    events:
      - http:
          path: ${self:custom.baseApi}/{eventId}
          method: get
          authorizer: ${self:custom.ms-account-authorizer}
          cors:
            origin: '*'
            headers: '*'
  updateEvent:
    handler: ${self:custom.funcDir}/updateEvent.handler
    events:
      - http:
          path: ${self:custom.baseApi}/
          method: put
          authorizer: ${self:custom.ms-account-authorizer}
          cors:
            origin: '*'
            headers: '*'
  deleteEvent:
    handler: ${self:custom.funcDir}/deleteEvent.handler
    events:
      - http:
          path: ${self:custom.baseApi}/{eventId}
          method: delete
          authorizer: ${self:custom.ms-account-authorizer}
          cors:
            origin: '*'
            headers: '*'